// * Booking
export const CHECK_AVAILABILITY_SUCCESS = 'CHECK_AVAILABILITY_SUCCESS';
export const CHECK_AVAILABILITY_ERROR = 'CHECK_AVAILABILITY_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
